{{-  range $k, $v := .Values.ingress.tls -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Release.Name }}-api-tls-{{ $v.secretName }}
spec:
  secretName: {{ $v.secretName }}
  issuerRef:
    name: {{ $v.issuerRef }}
    kind: ClusterIssuer
  dnsNames:
    {{- range $hk, $hv := $v.hosts }}
    - {{ $hv }}
    {{- end }}
---
{{- end -}}
