{{- if .Values.externalSecret -}}
{{- $fullName := include "nutrisense.fullname" . -}}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $fullName }}-external-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore.name }}
    kind: {{ .Values.externalSecret.secretStore.kind }}
  target:
    name: {{ .Release.Name }}-{{ .Values.envFile.name }}
    creationPolicy: {{ .Values.externalSecret.policy.creation }}
    deletionPolicy: {{ .Values.externalSecret.policy.deletion }}
  data:
    - secretKey: {{ .Values.envFile.key }}
      remoteRef:
        {{- range $k, $v := .Values.externalSecret.remoteRef }}
        {{ $k }}: {{ $v }}
        {{- end }}
{{- end -}}
