deploy: true

replicaCount: 1

image:
  repository: harbor.admin.tech/team/nutrisense/api
  pullPolicy: IfNotPresent
  tag: ""


imagePullSecrets:
  - name: team-rbac-setup-docker-pull-secret-team

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: nutrisense-service-account

externalSecret:
  secretStore:
    name: awsssm-store
    kind: ClusterSecretStore
  policy:
    creation: Owner
    deletion: Retain
  remoteRef:
    key: prod/nutrisense/env

envFile:
  name: envfile
  key: .env
  deploy: true

podAnnotations: {}

podSecurityContext: {}

securityContext:
  privileged: false
  seccompProfile:
    type: RuntimeDefault
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "ambassador"
  annotations: {}
  hosts:
    - host: api.nutrisense.prod.tech
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: nutrisense-service-prod-tls
      issuerRef: cluster-issuer-letsencrypt-issuer
      hosts:
        - api.nutrisense.prod.tech

resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 1
    memory: 2Gi

autoscaling:
  enabled: false
  minReplicas: 3
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

nodeSelector:
  kubernetes.io/arch: "arm64"

tolerations: []

affinity: {}

app:
  server:
    port: 8000
    env: production
    host: "::"
    ttl: 20s
  logger:
    level: info
  command: ["gunicorn", "--bind", "[::]:8000", "--workers", "4", "--chdir", "src", "main:flask_app",  "--timeout", "30", "--access-logfile",  "-"]

cronjobs: []
